"""
Cisco Configuration Generator
NetArchitect AI

Generates Cisco IOS-style configurations
from the generated NetworkPlan.
"""

from typing import Dict, Any, List


# ============================================================
# HELPER FUNCTIONS
# ============================================================

def get_vlan_ids(vlans: List[Dict[str, Any]]) -> List[int]:
    """Return VLAN IDs from the network plan."""

    return [
        vlan["vlan_id"]
        for vlan in vlans
        if vlan.get("vlan_id") is not None
    ]


def get_allowed_vlans(vlans: List[Dict[str, Any]]) -> str:
    """Create Cisco trunk VLAN list."""

    vlan_ids = get_vlan_ids(vlans)

    return ",".join(
        str(vlan_id)
        for vlan_id in vlan_ids
    )


def get_vlan_name(
    vlans: List[Dict[str, Any]],
    vlan_id: int
) -> str:
    """Get VLAN name by VLAN ID."""

    for vlan in vlans:
        if vlan.get("vlan_id") == vlan_id:
            return vlan.get(
                "name",
                f"VLAN-{vlan_id}"
            )

    return f"VLAN-{vlan_id}"


# ============================================================
# VLAN CONFIGURATION
# ============================================================

def generate_vlan_config(
    vlans: List[Dict[str, Any]]
) -> str:
    """Generate VLAN configuration."""

    config = []

    for vlan in vlans:

        vlan_id = vlan.get("vlan_id")

        if vlan_id is None:
            continue

        name = vlan.get(
            "name",
            f"VLAN-{vlan_id}"
        )

        config.extend([
            f"vlan {vlan_id}",
            f" name {name}",
            "!"
        ])

    return "\n".join(config)


# ============================================================
# SVI CONFIGURATION
# ============================================================

def generate_svi_config(
    ip_networks: List[Dict[str, Any]]
) -> str:
    """Generate Layer-3 SVI configuration."""

    config = []

    for network in ip_networks:

        vlan_id = network.get("vlan_id")
        gateway = network.get("gateway")

        subnet_mask = network.get(
            "subnet_mask",
            "255.255.255.0"
        )

        if vlan_id is None or not gateway:
            continue

        config.extend([
            f"interface vlan {vlan_id}",
            f" description Gateway-for-VLAN-{vlan_id}",
            f" ip address {gateway} {subnet_mask}",
            " no shutdown",
            "!"
        ])

    return "\n".join(config)


# ============================================================
# OSPF CONFIGURATION
# ============================================================

def generate_ospf_config(
    ip_networks: List[Dict[str, Any]],
    router_id: str = "1.1.1.1"
) -> str:
    """Generate OSPF configuration."""

    config = [
        "router ospf 1",
        f" router-id {router_id}"
    ]

    for network in ip_networks:

        network_address = network.get("network")

        if not network_address:
            continue

        # Currently supporting /24 networks.
        if network_address.endswith("/24"):

            network_address = network_address.replace(
                "/24",
                ""
            )

            wildcard = "0.0.0.255"

            config.append(
                f" network {network_address}"
                f" {wildcard} area 0"
            )

    config.append("!")

    return "\n".join(config)


# ============================================================
# CORE SWITCH
# ============================================================

def generate_core_switch_config(
    plan: Dict[str, Any]
) -> str:
    """Generate Core Switch configuration."""

    vlans = plan.get("vlans", [])
    ip_networks = plan.get("ip_networks", [])

    config = [
        "!",
        "! =========================================",
        "! CORE SWITCH CONFIGURATION",
        "! Generated by NetArchitect AI",
        "! =========================================",
        "!",
        "enable",
        "configure terminal",
        "hostname CORE-SWITCH",
        "!"
    ]

    # --------------------------------------------------------
    # VLANs
    # --------------------------------------------------------

    config.extend([
        "! VLAN CONFIGURATION",
        generate_vlan_config(vlans)
    ])

    # --------------------------------------------------------
    # SVIs
    # --------------------------------------------------------

    config.extend([
        "! LAYER 3 SVI CONFIGURATION",
        generate_svi_config(ip_networks)
    ])

    # --------------------------------------------------------
    # OSPF
    # --------------------------------------------------------

    routing_protocol = plan.get(
        "routing_protocol",
        ""
    ).upper()

    if routing_protocol == "OSPF":

        config.extend([
            "! OSPF CONFIGURATION",
            generate_ospf_config(
                ip_networks,
                router_id="1.1.1.1"
            )
        ])

    config.extend([
        "!",
        "end",
        "write memory",
        "!"
    ])

    return "\n".join(config)


# ============================================================
# DISTRIBUTION SWITCH
# ============================================================

def generate_distribution_switch_config(
    plan: Dict[str, Any],
    switch_number: int
) -> str:
    """Generate Distribution Switch configuration."""

    vlans = plan.get("vlans", [])

    allowed_vlans = get_allowed_vlans(vlans)

    config = [
        "!",
        "! =========================================",
        f"! DISTRIBUTION SWITCH {switch_number}",
        "! Generated by NetArchitect AI",
        "! =========================================",
        "!",
        "enable",
        "configure terminal",
        f"hostname DISTRIBUTION-SW-{switch_number}",
        "!"
    ]

    # VLANs
    config.extend([
        "! VLAN CONFIGURATION",
        generate_vlan_config(vlans)
    ])

    # Uplink
    config.extend([
        "! UPLINK TO CORE SWITCH",
        "interface GigabitEthernet0/1",
        " description Uplink-to-Core-Switch",
        " switchport mode trunk",
        f" switchport trunk allowed vlan {allowed_vlans}",
        " no shutdown",
        "!"
    ])

    # Example downstream trunk
    config.extend([
        "! DOWNLINK TO ACCESS SWITCHES",
        "interface GigabitEthernet0/2",
        " description Downlink-to-Access-Switch",
        " switchport mode trunk",
        f" switchport trunk allowed vlan {allowed_vlans}",
        " no shutdown",
        "!"
    ])

    config.extend([
        "end",
        "write memory",
        "!"
    ])

    return "\n".join(config)


# ============================================================
# ACCESS SWITCH
# ============================================================

def generate_access_switch_config(
    plan: Dict[str, Any],
    switch_number: int,
    ports_per_vlan: int = 4
) -> str:
    """
    Generate Access Switch configuration.

    Ports are distributed across the VLANs.

    Example with 5 VLANs and 4 ports per VLAN:

    VLAN 10 -> Gi0/2 - Gi0/5
    VLAN 20 -> Gi0/6 - Gi0/9
    VLAN 30 -> Gi0/10 - Gi0/13
    VLAN 40 -> Gi0/14 - Gi0/17
    VLAN 50 -> Gi0/18 - Gi0/21
    """

    vlans = plan.get("vlans", [])

    allowed_vlans = get_allowed_vlans(vlans)

    config = [
        "!",
        "! =========================================",
        f"! ACCESS SWITCH {switch_number}",
        "! Generated by NetArchitect AI",
        "! =========================================",
        "!",
        "enable",
        "configure terminal",
        f"hostname ACCESS-SW-{switch_number}",
        "!"
    ]

    # --------------------------------------------------------
    # VLAN CONFIGURATION
    # --------------------------------------------------------

    config.extend([
        "! VLAN CONFIGURATION",
        generate_vlan_config(vlans)
    ])

    # --------------------------------------------------------
    # UPLINK
    # --------------------------------------------------------

    config.extend([
        "! UPLINK TO DISTRIBUTION SWITCH",
        "interface GigabitEthernet0/1",
        " description Uplink-to-Distribution-Switch",
        " switchport mode trunk",
        f" switchport trunk allowed vlan {allowed_vlans}",
        " no shutdown",
        "!"
    ])

    # --------------------------------------------------------
    # ACCESS PORTS
    # --------------------------------------------------------

    current_port = 2

    for vlan in vlans:

        vlan_id = vlan.get("vlan_id")

        if vlan_id is None:
            continue

        vlan_name = vlan.get(
            "name",
            f"VLAN-{vlan_id}"
        )

        for _ in range(ports_per_vlan):

            # Prevent invalid ports.
            if current_port > 24:
                break

            config.extend([
                f"interface GigabitEthernet0/{current_port}",
                f" description {vlan_name}-End-User",
                " switchport mode access",
                f" switchport access vlan {vlan_id}",
                " spanning-tree portfast",
                " no shutdown",
                "!"
            ])

            current_port += 1

        if current_port > 24:
            break

    config.extend([
        "end",
        "write memory",
        "!"
    ])

    return "\n".join(config)


# ============================================================
# INTERNET ROUTER
# ============================================================

def generate_router_config(
    plan: Dict[str, Any]
) -> str:
    """Generate Internet Router configuration."""

    ip_networks = plan.get(
        "ip_networks",
        []
    )

    routing_protocol = plan.get(
        "routing_protocol",
        ""
    ).upper()

    config = [
        "!",
        "! =========================================",
        "! INTERNET ROUTER CONFIGURATION",
        "! Generated by NetArchitect AI",
        "! =========================================",
        "!",
        "enable",
        "configure terminal",
        "hostname INTERNET-ROUTER",
        "!",
        "! LAN INTERFACE",
        "interface GigabitEthernet0/0",
        " description Connection-to-Firewall",
        " no shutdown",
        "!",
        "! WAN INTERFACE",
        "interface GigabitEthernet0/1",
        " description Internet-Uplink",
        " no shutdown",
        "!"
    ]

    # --------------------------------------------------------
    # OSPF
    # --------------------------------------------------------

    if routing_protocol == "OSPF":

        config.extend([
            "! OSPF CONFIGURATION",
            generate_ospf_config(
                ip_networks,
                router_id="2.2.2.2"
            )
        ])

    config.extend([
        "!",
        "end",
        "write memory",
        "!"
    ])

    return "\n".join(config)


# ============================================================
# FIREWALL
# ============================================================

def generate_firewall_config(
    plan: Dict[str, Any]
) -> str:
    """Generate basic firewall configuration template."""

    config = [
        "!",
        "! =========================================",
        "! FIREWALL CONFIGURATION",
        "! Generated by NetArchitect AI",
        "! =========================================",
        "!",
        "! NOTE:",
        "! Firewall syntax depends on the vendor.",
        "! This is a generic Cisco-style template.",
        "!",
        "enable",
        "configure terminal",
        "hostname FIREWALL",
        "!",
        "! INSIDE INTERFACE",
        "interface GigabitEthernet0/0",
        " description Inside-Network",
        " no shutdown",
        "!",
        "! OUTSIDE INTERFACE",
        "interface GigabitEthernet0/1",
        " description Internet-Uplink",
        " no shutdown",
        "!",
        "! BASIC SECURITY POLICY",
        "!",
        "end",
        "write memory",
        "!"
    ]

    return "\n".join(config)


# ============================================================
# GENERATE ALL CONFIGURATIONS
# ============================================================

def generate_all_configurations(
    plan: Dict[str, Any]
) -> Dict[str, str]:
    """
    Generate configurations for all devices
    in the NetworkPlan.
    """

    configurations = {}

    devices = plan.get(
        "devices",
        []
    )

    # --------------------------------------------------------
    # CORE
    # --------------------------------------------------------

    core_exists = any(
        "Core Switch" in device.get(
            "device_type",
            ""
        )
        for device in devices
    )

    if core_exists:
        configurations["Core Switch"] = (
            generate_core_switch_config(plan)
        )

    # --------------------------------------------------------
    # DISTRIBUTION
    # --------------------------------------------------------

    distribution_count = 0

    for device in devices:

        device_type = device.get(
            "device_type",
            ""
        )

        if "Distribution Switch" in device_type:

            distribution_count = device.get(
                "quantity",
                1
            )

            break

    for i in range(
        1,
        distribution_count + 1
    ):

        configurations[
            f"Distribution Switch {i}"
        ] = generate_distribution_switch_config(
            plan,
            i
        )

    # --------------------------------------------------------
    # ACCESS
    # --------------------------------------------------------

    access_count = 0

    for device in devices:

        device_type = device.get(
            "device_type",
            ""
        )

        if "Access Switch" in device_type:

            access_count = device.get(
                "quantity",
                1
            )

            break

    for i in range(
        1,
        access_count + 1
    ):

        configurations[
            f"Access Switch {i}"
        ] = generate_access_switch_config(
            plan,
            i
        )

    # --------------------------------------------------------
    # ROUTER
    # --------------------------------------------------------

    router_exists = any(
        (
            "Router" in device.get(
                "device_type",
                ""
            )
            or
            "Internet Router" in device.get(
                "device_type",
                ""
            )
        )
        for device in devices
    )

    if router_exists:

        configurations[
            "Internet Router"
        ] = generate_router_config(plan)

    # --------------------------------------------------------
    # FIREWALL
    # --------------------------------------------------------

    firewall_exists = any(
        "Firewall" in device.get(
            "device_type",
            ""
        )
        for device in devices
    )

    if firewall_exists:

        configurations[
            "Firewall"
        ] = generate_firewall_config(plan)

    return configurations