
import { useEffect, useMemo } from "react";

import {
  ReactFlow,
  Background,
  Controls,
  MiniMap,
  useNodesState,
} from "@xyflow/react";

import "@xyflow/react/dist/style.css";
import "./NetworkTopology.css";

function getIcon(type = "") {
  const value = type.toLowerCase();

  if (value.includes("internet")) return "🌐";
  if (value.includes("router")) return "🌐";
  if (value.includes("firewall")) return "🛡️";
  if (value.includes("core")) return "🔷";
  if (value.includes("distribution")) return "🔀";
  if (value.includes("access")) return "🔌";
  if (value.includes("wireless")) return "📡";

  return "🖧";
}

function NetworkTopology({ plan }) {
  // Read the topology generated by the backend.
  const topology = plan?.topology_data;

  const generatedNodes = useMemo(() => {
    const backendNodes = topology?.nodes || [];

    // Arrange nodes by hierarchy level.
    const levels = {
      Internet: 0,
      Router: 1,
      Firewall: 2,
      Core: 3,
      Distribution: 4,
      Access: 5,
      Wireless: 6,
    };

    const getLevel = (type = "") => {
      const value = type.toLowerCase();

      if (value.includes("internet")) return levels.Internet;
      if (value.includes("router")) return levels.Router;
      if (value.includes("firewall")) return levels.Firewall;
      if (value.includes("core")) return levels.Core;
      if (value.includes("distribution")) return levels.Distribution;
      if (value.includes("access")) return levels.Access;
      if (value.includes("wireless")) return levels.Wireless;

      return 5;
    };

    const grouped = {};

    backendNodes.forEach((node) => {
      const level = getLevel(node.device_type);

      if (!grouped[level]) {
        grouped[level] = [];
      }

      grouped[level].push(node);
    });

    const result = [];

    Object.entries(grouped).forEach(([level, levelNodes]) => {
      const y = Number(level) * 150;
      const spacing = 220;

      levelNodes.forEach((node, index) => {
        const totalWidth = (levelNodes.length - 1) * spacing;
        const x = 500 - totalWidth / 2 + index * spacing;

        const vlanText =
          node.vlan_ids?.length > 0
            ? `VLANs: ${node.vlan_ids.join(", ")}`
            : "";

        result.push({
          id: node.node_id,
          position: { x, y },
          data: {
            label: (
              <div className="network-node">
                <div className="node-icon">
                  {getIcon(node.device_type)}
                </div>

                <strong>{node.label}</strong>

                {node.quantity > 1 && (
                  <span>Quantity: {node.quantity}</span>
                )}

                {vlanText && <span>{vlanText}</span>}
              </div>
            ),
          },
          style: {
            width: 190,
            padding: 12,
            borderRadius: 12,
            border: "2px solid #334155",
            background: "white",
          },
        });
      });
    });

    return result;
  }, [topology]);

  // Keep nodes draggable and update them when a new plan arrives.
  const [nodes, setNodes, onNodesChange] =
    useNodesState(generatedNodes);

  useEffect(() => {
    setNodes(generatedNodes);
  }, [generatedNodes, setNodes]);

  // Convert backend connections into React Flow edges.
  const edges = useMemo(() => {
    return (topology?.connections || []).map((connection, index) => ({
      id: `edge-${index}-${connection.source}-${connection.target}`,
      source: connection.source,
      target: connection.target,
      label: connection.connection_type,
      animated: connection.connection_type === "WAN",
    }));
  }, [topology]);

  if (!plan) {
    return null;
  }

  if (!topology?.nodes?.length) {
    return (
      <div className="topology-wrapper">
        <div className="topology-header">
          <div>
            <h2>Network Topology</h2>
            <p>Topology data is not available for this network plan.</p>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="topology-wrapper">
      <div className="topology-header">
        <div>
          <h2>Network Topology</h2>
          <p>
            Interactive topology generated from the backend network design
          </p>
        </div>
      </div>

      <div className="topology-container">
        <ReactFlow
          nodes={nodes}
          edges={edges}
          onNodesChange={onNodesChange}
          fitView
          nodesDraggable={true}
          nodesConnectable={false}
          elementsSelectable={true}
          panOnDrag={true}
          zoomOnScroll={true}
        >
          <Background />
          <Controls />
          <MiniMap />
        </ReactFlow>
      </div>
    </div>
  );
}

export default NetworkTopology;